library(data.table)
Data <- fread("/Users/AMOHY/household_power_consumption.txt",integer64 = "character")
Data <- as.data.frame(Data)
Data1 <- subset(Data,Data$Date=="1/2/2007" | Data$Date=="2/2/2007" )
Time<- paste(Data1$Date,Data1$Time)
plot(strptime(Time, '%d/%m/%Y %H:%M:%S'),as.numeric(Data1$Sub_metering_1),xlab='',ylab = "Energy sub metering",type="S")
points(strptime(Time, '%d/%m/%Y %H:%M:%S'),as.numeric(Data1$Sub_metering_2),col='red',type="S")
points(strptime(Time, '%d/%m/%Y %H:%M:%S'),as.numeric(Data1$Sub_metering_3),col='blue',type="S")
legend('topright',lwd=c(2.5,2.5),col=c("black","red","blue"),legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"))
dev.copy(png,file="plot3.png")
dev.off()